// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: grpc/proto/movie.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ImageUrl    string  `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Imdb        float32 `protobuf:"fixed32,3,opt,name=imdb,proto3" json:"imdb,omitempty"`
	ReleaseYear int32   `protobuf:"varint,4,opt,name=releaseYear,proto3" json:"releaseYear,omitempty"`
	Gender      string  `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Duration    string  `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Director    string  `protobuf:"bytes,7,opt,name=director,proto3" json:"director,omitempty"`
}

func (x *NewMovie) Reset() {
	*x = NewMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMovie) ProtoMessage() {}

func (x *NewMovie) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMovie.ProtoReflect.Descriptor instead.
func (*NewMovie) Descriptor() ([]byte, []int) {
	return file_grpc_proto_movie_proto_rawDescGZIP(), []int{0}
}

func (x *NewMovie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewMovie) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *NewMovie) GetImdb() float32 {
	if x != nil {
		return x.Imdb
	}
	return 0
}

func (x *NewMovie) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *NewMovie) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *NewMovie) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *NewMovie) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ImageUrl    string  `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Imdb        float32 `protobuf:"fixed32,3,opt,name=imdb,proto3" json:"imdb,omitempty"`
	ReleaseYear int32   `protobuf:"varint,4,opt,name=releaseYear,proto3" json:"releaseYear,omitempty"`
	Gender      string  `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Duration    string  `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Director    string  `protobuf:"bytes,7,opt,name=director,proto3" json:"director,omitempty"`
	Id          int32   `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_grpc_proto_movie_proto_rawDescGZIP(), []int{1}
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Movie) GetImdb() float32 {
	if x != nil {
		return x.Imdb
	}
	return 0
}

func (x *Movie) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Movie) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Movie) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Movie) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *Movie) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMoviesParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMoviesParams) Reset() {
	*x = GetMoviesParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesParams) ProtoMessage() {}

func (x *GetMoviesParams) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesParams.ProtoReflect.Descriptor instead.
func (*GetMoviesParams) Descriptor() ([]byte, []int) {
	return file_grpc_proto_movie_proto_rawDescGZIP(), []int{2}
}

type MovieList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies []*Movie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *MovieList) Reset() {
	*x = MovieList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_movie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieList) ProtoMessage() {}

func (x *MovieList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_movie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieList.ProtoReflect.Descriptor instead.
func (*MovieList) Descriptor() ([]byte, []int) {
	return file_grpc_proto_movie_proto_rawDescGZIP(), []int{3}
}

func (x *MovieList) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_grpc_proto_movie_proto protoreflect.FileDescriptor

var file_grpc_proto_movie_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x08, 0x4e, 0x65, 0x77,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x64, 0x62, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x69, 0x6d, 0x64, 0x62, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xcf, 0x01,
	0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x64,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x69, 0x6d, 0x64, 0x62, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x2b, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x32,
	0x62, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x25, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x12, 0x09, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x1a, 0x06, 0x2e, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_movie_proto_rawDescOnce sync.Once
	file_grpc_proto_movie_proto_rawDescData = file_grpc_proto_movie_proto_rawDesc
)

func file_grpc_proto_movie_proto_rawDescGZIP() []byte {
	file_grpc_proto_movie_proto_rawDescOnce.Do(func() {
		file_grpc_proto_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_movie_proto_rawDescData)
	})
	return file_grpc_proto_movie_proto_rawDescData
}

var file_grpc_proto_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_proto_movie_proto_goTypes = []interface{}{
	(*NewMovie)(nil),        // 0: NewMovie
	(*Movie)(nil),           // 1: Movie
	(*GetMoviesParams)(nil), // 2: GetMoviesParams
	(*MovieList)(nil),       // 3: MovieList
}
var file_grpc_proto_movie_proto_depIdxs = []int32{
	1, // 0: MovieList.movies:type_name -> Movie
	0, // 1: MovieManager.CreateNewMovie:input_type -> NewMovie
	2, // 2: MovieManager.GetMovies:input_type -> GetMoviesParams
	1, // 3: MovieManager.CreateNewMovie:output_type -> Movie
	3, // 4: MovieManager.GetMovies:output_type -> MovieList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_movie_proto_init() }
func file_grpc_proto_movie_proto_init() {
	if File_grpc_proto_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_movie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_movie_proto_goTypes,
		DependencyIndexes: file_grpc_proto_movie_proto_depIdxs,
		MessageInfos:      file_grpc_proto_movie_proto_msgTypes,
	}.Build()
	File_grpc_proto_movie_proto = out.File
	file_grpc_proto_movie_proto_rawDesc = nil
	file_grpc_proto_movie_proto_goTypes = nil
	file_grpc_proto_movie_proto_depIdxs = nil
}
