version: '3.4'
services: 
  app:
    build: .
    image: golang
    container_name: golang-api
    ports:
      - "8000"
    depends_on:
      - "mysql"  

  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=golangMovieApi
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - ./mysql:/var/lib/mysql
